
apiVersion: apps/v1
kind: Deployment
metadata:
  name: framed-docs
  labels:
    app: framed-docs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: framed-docs
  template:
    metadata:
      labels:
        app: framed-docs
    spec:
      containers:
      - name: framed-docs
        image: framed-docs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: framed-docs-service
spec:
  selector:
    app: framed-docs
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: framed-docs-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: framed-docs-service
            port:
              number: 80
